- .github/workflows/march-image-build-push.yml
This should give us official builds in quay.io.
Fixes #12
> :seedling: Setup multi-arch builds

- cmd/rules.go
The RuleSet Rules files are written into a newly created directory, dedicated named using the RuleSet.ID.  Adding the prefix in an effort to avoid name collisions isn't needed and cause a problem with specially named files like `ruleset.yaml`.
As a result, the analyzer ignores the ruleset (and all of its rules) because it cannot find the `ruleset.yaml'.
This results in no issues created.
> :bug: Fix ruleset not found.

- builder/issue.go
- cmd/analyzer.go
- cmd/main.go
- cmd/rules.go
- go.mod
- go.sum
Appends analyzer reported errors to the TaskReport.Errors.
Prevent downloading duplicate rulesets.
closes: #26
> :sparkles: Improved analyzer errors reporting.

- Makefile
- builder/deps.go
- builder/issue.go
- cmd/settings.go
- go.mod
- go.sum
- hack/README.md
- hack/konveyor-analyzer
- hack/konveyor-analyzer-dep
- hack/reset
fixes: #24 
Adds (2) shell scripts to run the analyzer in docker.  Handy when running the addon locally.
> :bug: Fixes YAML encoding/decoding issue for codeSnip.

- Dockerfile
- cmd/rules.go
- go.mod
- go.sum
- hack/README.md
- hack/windup-shim
- settings.json
Run windup-shim on rules/ which converts windup rules which are written into rules/converted.
Also:
- latest hub binding.
- latest analyzer-lsp image.  Minor change for campat with provider settings API.
closes: #8
> :sparkles: Run windup-shim.

- cmd/analyzer.go
- cmd/settings.go
Set provider proxy settings.
Note: both http and https proxies are seeded.  They are only used when `host` is populated.
closes #21
> :sparkles: propagate proxy settings.

- cmd/analyzer.go
- cmd/mode.go
Pass `--no-dependency-rules` to the analyzer for source (only) mode.
Added Mode.WithKnownLibs (bool). 
When FALSE (default), pass `--dep-label-selector !konveyor.io/dep-source=open-source` to the analyzer-dep.
> :ghost: get/pass maven settings for all source modes.

- cmd/rules.go
For each ruleset dependency (ruleset), the addon inspects the rules for labels and adds them to the selector.  Some of the rules have wildcard _source_ and _target_ labels which must not be included in the selector.
The solution is to update seeded (dependency) rulesets to have:
```
- konveyor.io/source
- konveyor.io/target
```
This removes the `discovery` and other _special_ labels that are not useful when used in konveyor.
The tackle2-seed will need to be updated.
--- 
unrelated, I noticed while testing that Label methods needed a patch.
> :bug: Discontinue injecting labels.

- builder/issue.go
Fixes blank Incident.File.
The analyzer creates URIs with custom schemes which is not compatible with the Go [uri](https://pkg.go.dev/go.lsp.dev/uri) package which only supports (file,http,https).  Using the [url](https://pkg.go.dev/net/url) package to parse instead is safe because the `uri` package uses the `url` internally anyway.  Fall back on _raw_ URI string on parsing error.
> :bug: : Handle incident URI with custom schemes.

- cmd/mode.go
https://github.com/konveyor/analyzer-lsp/issues/318#issuecomment-1716318254
When _with-known-libraries_ is not requested:
```
- '[CMD] Running: /usr/bin/konveyor-analyzer --provider-settings /addon/opt/settings.json --output-file /addon/report.yaml --dep-label-selector !konveyor.io/dep-source=open-source --rules /addon/rules/rulesets/1/rules --rules /addon/rules/rulesets/18/rules --rules /addon/rules/rulesets/22/rules --rules /addon/rules/rulesets/19/rules --rules /addon/rules/converted --label-selector (konveyor.io/target=cloud-readiness||konveyor.io/target=linux)'
```
> :bug: --dep-label-selector passed to analyzer.

- cmd/mode.go
- cmd/scope.go
This attribute should have been implemented under `scope`.
> :bug: Fix withKnownLibs setting.

- cmd/rules.go
This excludes the target and source wildcard labels, but adds any other labels from the dependency rulesets to the set to be included.
> :bug: Add filtered labels from dependency rulesets

- cmd/rules.go
Reverts konveyor/tackle2-addon-analyzer#47
Will be fixed in rulesets with _special always_ label TBD.
Requires: 
- https://github.com/konveyor/rulesets/pull/18
- tackle2-seed rulesets PR TBD.
> Revert ":bug: Add filtered labels from dependency rulesets"

- .github/workflows/ci.yaml
This PR integrates a GitHub Action workflow to build and upload the component images, preparing them for the global CI system. 
By integrating the global CI, we aim to streamline and standardize our CI process across all components, ensuring a more efficient and unified CI/CD pipeline.
> :seedling: Integrate global-ci workflow

- cmd/rules.go
Not sure what changed in the shim (or rulesets) but using :latest, the output directory is only created when rules are converted.  Better practice to not rely on the shim creating it.
Fixes:
```
errors:
- severity: Error
description: 'open /addon/rules/converted: no such file or directory'
- severity: Error
description: 'Pod failed: Error'
```
> :bug: ensure converted directory is created.

- builder/deps.go
Propagate dep provider and labels.
> :bug: Propagate dep labels.

- go.mod
- go.sum
Latest tackle2-addon command with RunSilent() that does not fail silently.
Example:
```
errors:
- severity: Error
description: exit status 1
- severity: Error
description: 'Pod failed: Error'
activity:
- Fetching application.
- '[CMD] Running: /usr/bin/ssh-agent -a /tmp/agent.736692'
- '[CMD] succeeded.'
- '[SSH] Agent started.'
- '[MVN] Using settings file(path=/home/jortel/tmp/addon/settings.xml).'
- '[SVN] Cloning: http://3.19.255.219/repos/trunk'
- '[SVN] Using credentials (id=3) SVN.'
- '[CMD] /usr/bin/svn failed: exit status 1.'
- '> svn: warning: W170000: URL ''http://3.19.255.219/repos/trunk'' non-existent in revision 3'
- '> '
- '> svn: E200009: Could not display info for all targets because some targets don''t exist'
- '> '
```
> :bug: Latest tackle2-addon.

- README.md
- doc/hub.md
Analyzer-lsp is spelled with a `z` not an `s`, so I figured it would be best to keep the spelling consistent across the project.
> :bug: Fixed spelling

- cmd/cmd_test.go
- cmd/scope.go
Add support for incident selectors.  Users can filter in/out incidents based on packages. The `package` is reported as an Incident.Variables with key=`package`.
The `!package` and ` !(package)` syntax is used to match incidents without the _package_ variable.
Passes `--incident-selector` option as needed.
Test cases and expected selector:
| Case | Selector |
| --------- | ---------- |
| Empty |   |
|Included (only)| (!package\|\|package=a\|\|package=b) |
| Included and Excluded|(!package\|\|package=a\|\|package=b) && !(package=C\|\|package=D)|
|Excluded (only)|!(package\|\|package=C\|\|package=D)|
> :bug: Support incident selectors.

- go.mod
- go.sum
Fixed by: https://github.com/konveyor/tackle2-addon/pull/51
fixes: #71
> :bug: Fix issue 71, maven command.

- cmd/rules.go
The addon is passing non-YAML files in --rules option to the analyzer.  For example: when custom targets built with uploaded windup.xml files.
This does not seem to hurt anything. The analyzer output mentions that it cannot be parsed as YAML but does not error. Fixing will mainly avoid: confusion; red-herrings while troubleshooting.
> :bug: Passing non-YAML files with --rules option.

- Makefile
- builder/deps.go
- builder/issue.go
- cmd/analyzer.go
- cmd/cmd_test.go
- cmd/rules.go
- cmd/scope.go
- cmd/settings.go
- cmd/tagger.go
- go.mod
- go.sum
upgrade Go 1.20.
Replaces gofmt with goimports. Documentation claims it performs the same formatting plus manages/orders imports.
Added missing packages in Makefile.
Updated the go.mod and ran go mod tidy.
closes: #63 
NOT FOR 0.3.
> :ghost: Go 1.20

- cmd/analyzer.go
- hack/README.md
- hack/konveyor-analyzer
- hack/konveyor-analyzer-dep
- settings.json
Moving the non system binaries to /usr/local/bin
> :bug: Fixing up the addon to use the updated location for bin

- cmd/injector.go
The java extension CR defines:
```
resources:
- fields:
- key: maven.settings.path
name: settings
path: /shared/creds/maven/settings.xml
selector: identity:kind=maven
```
`/shared` exists but `creds/maven` needs to be created on demand.
Reported by CI as:
```
"errors": [
{
"severity": "Error",
"description": "open /shared/creds/maven/settings.xml: no such file or directory"
}
],
```
> :bug: Create intermediate path for resources stored as files.

- cmd/mode.go
Short-term workaround.
The UI merged a PR to prefixes the Application.Binary with "mvn://".  This PR is a fall-back until #97 can be merged which requires an analyzer patch to fix the builtin provider.
> :bug: strip mvn:// prefix. This is a short-term workaround.

- cmd/tagger.go
Reverts konveyor/tackle2-addon-analyzer#104
> Revert ":bug: Use tag source from Tagger"

- cmd/analyzer.go
Attach analyzer report when verbosity > 0 to better support troubleshooting.
https://issues.redhat.com/browse/MTA-1457
> :sparkles: Attach analyzer report when verbosity > 0.

- cmd/main.go
- go.mod
- go.sum
Errors listed by the analyzer in the report (errors array) are reported by the addon as TaskReport errors but the TaskReport.Status is not set to `Failed`.
Requires: https://github.com/konveyor/tackle2-hub/pull/681
> :sparkles: Support succeeded with addon rule errors.

- builder/deps.go
- builder/issue.go
In support of succeeded-with-errors, the addon should report issues (violations) even when the ruleset reports errors.
Also fixes duplicate rule errors added to the Task.Errors.
> :bug: Report violations for ruleset with errors.

- builder/issue.go
- cmd/main.go
To support succeeded with errors, the RuleError cannot be returned in the builder stream because it is interpreted as a streaming error by the multi-part form send.
related: https://github.com/konveyor/tackle2-hub/pull/729
closes #114
> :bug: Report ruleErr outside of builder stream.

- go.mod
- go.sum
ref: https://github.com/konveyor/tackle2-addon/pull/63
> :sparkles: Latest addon with git optimization.

- cmd/rules.go
https://issues.redhat.com/browse/MTA-3330
A custom target that references a repository will be created with a related `RuleSet`. A repository may be defined on the ruleSet. An analysis task defines _included_ labels which determine which rulesets are pulled (downloaded) from the hub.  Since ruleSets that reference repositories do not have labels, the addon did not know to download it and clone the repository.
Solution:
The new rules.ruleSets will be used to pass a list of RuleSet (refs) selected by the user (by selecting targets).  Each will be be unconditionally fetched by the addon.
For each ruleset with a repository the addon will:
- clone the repository
- update .yaml files - replacing the `labels` element with `konveyor.io/include=always`.
related: …
> :bug: Fix Targets (Rulesets) with repositories.

- builder/deps.go
closes #121 
The `addon.Activity()` reports addon activity which is appended to the TaskReport.Activity using a PUT.  This will briefly acquire a DB transaction (in the hub).
The builder MUST not report activity because the addon already has a transaction open in the hub because of the POST of the analysis report.  This creates a DEADLOCK.
**There is a race-condition**: This only happens when the hub begins the transaction before the dep writer reports the dep.yaml not found.  I can force this by adding a sleep to where the writer reports this.  I suspect the hub can be busy enough with UI GET requests to delay it beginning the analysis POST until after the builder reports the file not found.
Flow:
```
addon                    hub
| post analysis ----- >|  
|                      | begin …
```
> :bug: Fix transaction deadlock in dep builder.

- cmd/main.go
- cmd/mode.go
- go.mod
- go.sum
Capture the commit and include in the Analysis.
> :sparkles: KAI support.

- cmd/rules.go
Ensure each _ruleDir_ (`--rules`) contains a `ruleset.yaml`.
Run the shim on all _ruleDir_.  This includes rules/files which contains uploaded individual rule files.
This is needed because the shim creates converted files in the root of the output dir.
https://issues.redhat.com/browse/MTA-3163
https://issues.redhat.com/browse/MTA-3330
> :bug: Run the shim on each directory.

- builder/deps.go
- builder/issue.go
- builder/manifest.go
- cmd/analyzer.go
- cmd/main.go
- go.mod
- go.sum
Upload issues and deps files instead of using multi-part form.
Much simpler and more easily supports the addon staging the issues and deps files on disk rather than streaming. The more atomic approach will prevent transaction deadlock which can more easily occur when the addon-analyzer builder reported an error (which it should never do).
Requires: https://github.com/konveyor/tackle2-hub/pull/743
> :sparkles: Upload files instead of multi-part form.

- .github/workflows/ci.yaml
- Dockerfile
- Makefile
- go.mod
- go.sum
Signed-off-by: Jason Montleon <jmontleo@redhat.com>
(cherry picked from commit 9264d55b908d9579ebc5d82115fd904ede22ed01)
> :sparkles: Add SSH config to run rootless non-interactively (#133)

- go.mod
- go.sum
Latest addon Subversion to better support branches and tags.
Also, implements Head() to support KAI.
> :bug: updated svn to support tags and head.

- cmd/injector.go
Support injecting _general_ settings (Resources) into extension configuration.
Example:
```
metadata:
provider:
address: localhost:$(PORT)
initConfig:
- providerSpecificConfig:
mavenInsecure: $(maven.insecure)
mavenSettingsFile: $(maven.settings.path)
name: java
resources:
- fields:
- key: maven.settings.path
name: settings
path: /shared/creds/maven/settings.xml
selector: identity:kind=maven
- fields:
- key: maven.insecure
name: value
selector: setting:key=mvn.insecure.enabled
```
> :sparkles: inject setting resources.

- cmd/cmd_test.go
- cmd/injector.go
Inject variables using true or _cast_ types when variable references not embedded in other text.
Consider:
```
metadata:
provider:
address: localhost:$(PORT)
initConfig:
- providerSpecificConfig:
mavenInsecure: $(maven.insecure)
mavenSettingsFile: $(maven.settings.path)
name: java 
resources:
- selector: identity:kind=maven
fields:
- key: maven.settings.path
name: settings
path: /shared/creds/maven/settings.xml
- selector: setting:key=mvn.insecure.enabled
fields:
- key: maven.insecure
name: value
```
For example:
```
mavenInsecure = $(maven.insecure)
```
$(maven.insecure) has a _true_ type of boolean (as stored in the db) so it will be injected as:
```yaml
mavenInsecure: true
```
For cases when the _true_ type is different,  an optional `type` field may be used to cast.  In the previous …
> :sparkles: Inject typed values.

- .github/workflows/ci.yaml
- Makefile
- cmd/analyzer.go
- cmd/cmd_test.go
- cmd/injector.go
- cmd/mode.go
- cmd/settings.go
Add support for injecting the source code path (to be analyzed) in the extension metadata.  The `Location` field will continue to be injected.  There are providers that do not honor the Location field but instead expect a `workspaceFolders` array populated.  This is an inconsistency in providers.  To support this, the location needs to be templated. A new `location` variable in the `builtin` namespace may be used by the extension writer.
Example:
```
metadata:
provider:
address: localhost:$(PORT)
initConfig:
- providerSpecificConfig:
lspServerName: generic
lspServerPath: /usr/local/bin/pylsp
workspaceFolders:
- $(builtin.location)                  <-------------- HERE
dependencyFolders:
- examples/python/__pycache__
- examples/python/.venv
name: python
```
> :sparkles: Inject location

- .github/workflows/ci.yaml
- builder/deps.go
- builder/issue.go
- cmd/analyzer.go
- hack/examples/deps.yaml
- hack/examples/issues-with-errors.yaml
- hack/examples/issues.yaml
- hack/konveyor-analyzer
The Issues and Deps report builders need to be returned by the `Analyzer.Run()` facade having already read the analyzer output files. This ensures the files are only read once and methods may be invoked in any order.
This is a regression introduced in 0.6.0.
---
Add hack analyzer script to better support running the addon locally for testing.
---------
> :bug: Fix analyzer error relay to task. (#144)

- cmd/cmd_test.go
- cmd/rules.go
Support excluded labels in the rule selector.
```
rules:
labels:
excluded:
- noincludejsp
included:
- konveyor.io/target=containerization
- konveyor.io/target=linux
```
produces selector:
```
(konveyor.io/target=containerization||konveyor.io/target=linux)&&!noincludejsp
```
---
```
rules:
labels:
excluded:
- noincludejsp
- noincludelx
included:
- konveyor.io/target=containerization
- konveyor.io/target=linux
```
produces selector:
```
(konveyor.io/target=containerization||konveyor.io/target=linux)&&!(noincludejsp||noincludelx)
```
Related to: https://issues.redhat.com/browse/MTA-4973
--- 
No longer trimming the outside (). This was being done in an effort to reduce _noise_ in the selector in some cases. Not worth the even minor complexity and had a non-zero chance of causing a problem.
> :bug: Support excluded labels.
